fos_oauth_server:
  db_driver: orm
  client_class: App\Entity\Client
  access_token_class: App\Entity\AccessToken
  refresh_token_class: App\Entity\RefreshToken
  auth_code_class: App\Entity\AuthCode
  service: 
    user_provider: fos_user.user_provider.username
    options: 
      access_token_lifetime: 86400
      refresh_token_lifetime: 12096000
      auth_code_lifetime: 30